# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
    - name: Cloudflare Pages GitHub Action
      uses: cloudflare/pages-action@v1.5.0
      with:
        # Cloudflare API Token
        apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        # Cloudflare Account ID
        accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        # The name of the Pages project to upload to
        projectName: 'ng-testing-practice'
        # The directory of static assets to upload
        directory: 'dist/ng-testing-practice'

