# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set Node.JS
      uses: actions/setup-node@v4
      with:
        node-version: 18
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - name: Cloudflare Pages GitHub Action
      uses: cloudflare/pages-action@v1.5.0
      with:
        # Cloudflare API Token
        apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        # Cloudflare Account ID
        accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        # The name of the Pages project to upload to
        projectName: 'ng-testing-practice'
        # The directory of static assets to upload
        directory: './dist/zoneless-calculator/browser'
        branch: 'main'

